server:
  port: 7476
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.142.113.254:1103/club_online_db
    username: root
    password: wxzxgsybD_P258852
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.qq.com
    username: 1507410636@qq.com
    password: ldkxisghibjxideg
    protocol: smtp
    # smtp 的指定端口 使用 465 要将 protocol 改为 smtps
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        debug: false
        smtp:
          ssl:
            enable: true
          auth: true
          socketFactory:
            # 这个可要可不要
            # class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
  redis:
    host: 43.142.113.254
    port: 6379
    password: wxzxgsybD_P258852
    database: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
agile:
  kaptcha:
    enable: true
    live-time: 120s
    token-header: v-code
    url: /permission/captcha


